---
title: Загублені в космосі
hero_image: images / lost-in-space.png
description: Дізнайтеся, як програмувати власну анімацію!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4
last_tested: 2018-09-26
steps:
  - 
    title: Введення
  - 
    title: Анімація космічного корабля
  - 
    title: 'Challenge: improve your animation'
    challenge: true
  - 
    title: Animation using loops
  - 
    title: Плаваюча мавпа
  - 
    title: Астероїд, що стрибає
  - 
    title: Сяюча зірка
  - 
    title: 'Завдання: створіть власну анімацію'
    challenge: true
  - 
    title: Test yourself
  - 
    title: What next?
