---
title: Verdwaald in de ruimte
hero_image: images/lost-in-space.png
description: Leer hoe je je eigen animatie kunt programmeren!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4
last_tested: 2017-11-01
steps:
  - 
    title: Inleiding
  - 
    title: Wat je nodig hebt
  - 
    title: 'Een ruimteschip animeren'
    challenge: true
  - 
    title: Animeren met behulp van lussen
  - 
    title: Zwevende aap
  - 
    title: Stuiterende asteroïde
  - 
    title: Fonkelende ster
  - 
    title: 'Uitdaging: maak je eigen animatie'
    challenge: true
  - 
    title: What next?
