---
title: जागेत हरवले
theme: हिरवा
hero_image: प्रतिमा / गहाळ-इन-स्पेस.png
description: 'आपल्या स्वत: च्या अॅनिमेशनवर कसे प्रोग्राम करावे ते जाणून घ्या!'
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
duration: 2
listed: true
copyedit: true
ingredient: false
curriculum: 1, डिझाइन -1, प्रोग्रामिंग -1, फेज- comp-0, उत्पादन 0, समुदाय-0
interests: जागा
technologies: सुरवातीपासून
site_areas: प्रकल्प
hardware: ''
software: सुरवातीपासून
version: 4
last_tested: 2017-11-01
steps:
  - 
    title: परिचय
  - 
    title: आपल्याला कशाची आवश्यकता लागेल
  - 
    title: स्पेसशिप अॅनिमेटिंग
  - 
    title: लूप वापरून अॅनिमेटिंग
  - 
    title: फ्लोटिंग म बंदर
  - 
    title: शेपूट लघुग्रह
  - 
    title: चमकणारा तारा
  - 
    title: 'आव्हान: आपल्या स्वत: च्या अॅनिमेशन करा'
