---
title: Потерянный в космосе
hero_image: Изображения / потерянных в-space.png
description: Узнайте, как программировать собственную анимацию!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: царапина
version: 4.1.3
last_tested: 2018-09-26
steps:
  - 
    title: Введение
  - 
    title: Animating a spaceship
  - 
    title: 'Challenge: improve your animation'
    challenge: true
  - 
    title: Animation using loops
  - 
    title: Плавающая обезьяна
  - 
    title: Отскок астероида
  - 
    title: Сияющая звезда
  - 
    title: 'Задача: создать собственную анимацию'
    challenge: true
  - 
    title: What next?
