---
title: Изгубљени у свемиру
hero_image: имагес / лост-ин-спаце.пнг
description: Научићеш како да програмираш сопствену анимацију!
original_url: хттпс://ввв.цодецлубпројецтс.орг/ен-ГБ/сцратцх/лост-ин-спаце
listed: true
copyedit: true
technologies: сцратцх
version: 4
last_tested: 2017-11-01
steps:
  - 
    title: Изгубљени у свемиру
  - 
    title: Анимирање свемирског брода
  - 
    title: 'Изазов: побољшајте своју анимацију'
    challenge: true
  - 
    title: Анимација помоћу петље
  - 
    title: Плутајући мајмун
  - 
    title: Боунцинг астероид
  - 
    title: Схининг стар
  - 
    title: 'Изазов: направите сопствену анимацију'
    challenge: true
  - 
    title: Шта даље?
