---
title: Fortapt i verdensrommet
hero_image: images/lost-in-space.png
description: Lær hvordan du programmerer din egen animasjon!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4.1.3
last_tested: 2018-09-26
steps:
  - 
    title: Introduksjon
  - 
    title: Animere et romskip
  - 
    title: 'Utfordring: gjør animasjonen din bedre'
    challenge: true
  - 
    title: Animasjon med løkker
  - 
    title: Svevende apekatt
  - 
    title: Sprettende asteroide
  - 
    title: Skinnende stjerne
  - 
    title: 'Utfordring: lag din egen animasjon'
    challenge: true
  - 
    title: Hva nå?
