---
title: Bị mất trong không gian
hero_image: images / lost-in-space.png
description: Tìm hiểu cách lập trình hoạt ảnh của riêng bạn!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: vết trầy
version: 4.1.3
last_tested: 2018-09-26
steps:
  - 
    title: Giới thiệu
  - 
    title: Hoạt hình một tàu vũ trụ
  - 
    title: 'Thách thức: cải thiện hoạt hình của bạn'
    challenge: true
  - 
    title: Hoạt hình sử dụng các vòng lặp
  - 
    title: Khỉ nổi
  - 
    title: Nảy tiểu hành tinh
  - 
    title: Ngôi sao sáng
  - 
    title: 'Thách thức: tạo hoạt ảnh của riêng bạn'
    challenge: true
  - 
    title: Tiếp theo là gì?
