---
title: Məkanında itirdi
hero_image: images / itirilmiş-in-space.png
description: Öz animasiyalarınızı necə tərtib edəcəyinizi öyrənin!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: cızıq
version: 4.1.3
last_tested: 2018-09-26
steps:
  - 
    title: Giriş
  - 
    title: Animating a spaceship
  - 
    title: 'Challenge: improve your animation'
    challenge: true
  - 
    title: Animation using loops
  - 
    title: Üzən meymun
  - 
    title: Asteroidin zərbəsi
  - 
    title: Ulduz parıldadıb
  - 
    title: 'Challenge: öz animasiya edin'
    challenge: true
  - 
    title: Test yourself
  - 
    title: What next?
