---
title: Məkanında itirdi
theme: yaşıl
hero_image: images / itirilmiş-in-space.png
description: Öz animasiyalarınızı necə tərtib edəcəyinizi öyrənin!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
duration: 2
listed: true
copyedit: true
ingredient: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: space
technologies: cızıq
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-11-01
steps:
  - 
    title: Giriş
  - 
    title: Nə lazımdır?
  - 
    title: Bir uzay gemisini hərəkət etdirmək
  - 
    title: Döngələri istifadə edərək animasiya
  - 
    title: Üzən meymun
  - 
    title: Asteroidin zərbəsi
  - 
    title: Ulduz parıldadıb
  - 
    title: 'Challenge: öz animasiya edin'
