---
title: Perdido no espaço
hero_image: images/lost-in-space.png
description: Aprende a programar o teu próprio robot falante!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4.1.3
last_tested: 2018-09-26
steps:
  - 
    title: Introdução
  - 
    title: Animando uma nave espacial
  - 
    title: 'Desafio: melhorar a animação'
    challenge: true
  - 
    title: Animação utilizando ciclos
  - 
    title: Macaco flutuante
  - 
    title: Asteróide saltitante
  - 
    title: Estrela Brilhante
  - 
    title: 'Desafio: adiciona as tuas imagens'
    challenge: true
  - 
    title: O que se segue?
