---
title: Izgubljeni u svemiru
hero_image: images/lost-in-space.png
description: U ovom projektu naučit ćeš programirati svoje animacije!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4
last_tested: 2018-09-26
steps:
  - 
    title: Sretan rođendan
  - 
    title: Animating a spaceship
  - 
    title: 'Challenge: improve your animation'
    challenge: true
  - 
    title: Animation using loops
  - 
    title: Floating monkey
  - 
    title: Bouncing asteroid
  - 
    title: Shining star
  - 
    title: 'Challenge: make your own animation'
    challenge: true
  - 
    title: What next?
