---
title: Izgubljeni u svemiru
hero_image: images/lost-in-space.png
description: U ovom projektu naučit ćeš programirati svoje animacije!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4
last_tested: 2018-09-26
steps:
  - 
    title: Sretan rođendan
  - 
    title: Animacija svemirskog broda
  - 
    title: 'Izazov: poboljšaj svoju animaciju'
    challenge: true
  - 
    title: Animacija pomoću petlje
  - 
    title: Plutajući majmun
  - 
    title: Odskakanje asteroida
  - 
    title: Blistajuća zvijezda
  - 
    title: 'Izazov: napravite vlastitu animaciju'
    challenge: true
  - 
    title: Što dalje?
