---
title: Kadonnut avaruudessa
hero_image: Kuvien / menetetty-in-space.png
description: Opi animaation ohjelmointi!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: naarmu
version: 4.1.3
last_tested: 2018-09-26
steps:
  - 
    title: esittely
  - 
    title: Animating a spaceship
  - 
    title: 'Challenge: improve your animation'
    challenge: true
  - 
    title: Animation using loops
  - 
    title: Kelluva apina
  - 
    title: Pomppiva asteroidi
  - 
    title: Loistava tähti
  - 
    title: 'Haaste: tee oma animaatio'
    challenge: true
  - 
    title: What next?
