---
title: Perdidos en el Espacio
theme: green
hero_image: images/lost-in-space.png
description: ¡Aprende a programar tu propia animación!
original_url: https://projects.raspberrypi.org/en/projects/lost-in-space
duration: 2
listed: true
copyedit: true
ingredient: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: space
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-11-01
steps: 
- title: Introducción
- title: Animar una nave espacial
- title: Animar usando bucles
- title: Mono flotante
- title: Asteroides que rebotan
- title: Estrellas que brillan
- title: "Desafío: Crea tu propia animación"