---
title: Ar Goll yn y Gofod
hero_image: images/lost-in-space.png
description: Dysgwch sut i raglennu eich animeiddiad eich hunan!
original_url: https://projects.raspberrypi.org/en/projects/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4
last_tested: 2017-11-01
steps:
  - 
    title: Cyflwyniad
  - 
    title: Animeiddio llong ofod
  - 
    title: 'Animeiddio gan ddefnyddio dolennu'
    challenge: true
  - 
    title: Mwcni yn Arnofio
  - 
    title: Asteroid Sbonciog
  - 
    title: Sêr Disglair
  - 
    title: 'Her: Gwna amineddiad dy hunan'
  - 
    title: 'Her: gwneud dy animeiddiad dy hunan'
    challenge: true
  - 
    title: Test yourself
  - 
    title: What next?
