---
title: Pierdut in spatiu
hero_image: images / pierdut-in-space.png
description: Vei învăța cum să faci propria ta animație!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: zgârietură
version: 4
last_tested: 2017-11-01
steps:
  - 
    title: Lost in space
  - 
    title: Animând o navă spațială
  - 
    title: 'Provocare: îmbunătățiți animația'
    challenge: true
  - 
    title: Animație folosind bucle
  - 
    title: Floarea maimuță
  - 
    title: Bomba asteroidului
  - 
    title: Stea stralucitoare
  - 
    title: 'Provocare: creați propria animație'
    challenge: true
  - 
    title: Test yourself
  - 
    title: What next?
