---
title: Pierdut in spațiu
hero_image: images / pierdut-in-space.png
description: Învață cum să programezi propria ta animație!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: zgârietură
version: 4
last_tested: 2017-11-01
steps:
  - 
    title: Introducere
  - 
    title: Să animăm o navă spațială
  - 
    title: 'Provocare: îmbunătățește-ți animația'
    challenge: true
  - 
    title: Animația folosind bucle
  - 
    title: Maimuța plutitoare
  - 
    title: Asteroidul săltăreț
  - 
    title: Stea strălucitoare
  - 
    title: 'Provocare: creați propria animație'
    challenge: true
  - 
    title: Ce urmează?
