---
title: Perdido no espaço
hero_image: images/lost-in-space.png
description: Aprenda a programar sua própria animação!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4
last_tested: 2018-09-26
steps:
  - 
    title: Introdução
  - 
    title: Animando uma nave espacial
  - 
    title: 'Animando uma nave espacial'
    challenge: true
  - 
    title: Animando usando repetições
  - 
    title: Macaco flutuante
  - 
    title: Asteroide viajante
  - 
    title: Estrela brilhante
  - 
    title: 'Desafio: Faça a sua própria animação'
    challenge: true
  - 
    title: What next?
