---
title: Perdido no espaço
theme: verde
hero_image: images/lost-in-space.png
description: Aprenda a programar sua própria animação!
original_url: http://projects.codeclubworld.org/pt-BR/01_scratch_01/02/Lost in Space.html
duration: 2
listed: true
copyedit: true
ingredient: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: space
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-11-01
steps:
  - 
    title: Introduction
  - 
    title: What you will need
  - 
    title: Animating a spaceship
  - 
    title: Animating using loops
  - 
    title: Floating monkey
  - 
    title: Bouncing asteroid
  - 
    title: Shining star
  - 
    title: 'Challenge: make your own animation'
