---
title: خلا میں کھو دیا
theme: سبز
hero_image: تصاویر / کھوئے ہوئے میں جگہ
description: جانیں کہ کس طرح آپ کی حرکت پذیری پروگرام کا پروگرام ہے!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
duration: 2
listed: true
copyedit: true
ingredient: false
curriculum: 1، ڈیزائن-0، پروگرامنگ -1، فیز-کمپ-0، تیاری-0، کمیونٹی-0
interests: جگہ
technologies: خرگوش
site_areas: منصوبوں
hardware: ''
software: خرگوش
version: 4
last_tested: 2017-11-01
steps:
  - 
    title: تعارف
  - 
    title: آپ کی ضرورت ہو گی
  - 
    title: ایک جہاز حرکت پذیری
  - 
    title: loops کا استعمال کرتے ہوئے حرکت پذیری
  - 
    title: فلوٹنگ بندر
  - 
    title: اسٹرائیوڈ شیخی
  - 
    title: روشن ستارہ
  - 
    title: 'چیلنج: اپنا اپنا حرکت پذیری بنائیں'
