---
title: Hilang dalam ruang
hero_image: gambar / hilang-dalam-ruang.png
description: Pelajari cara memprogram animasi Anda sendiri!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: menggaruk
version: 4.1.3
last_tested: 2018-09-26
steps:
  - 
    title: pengantar
  - 
    title: Animating a spaceship
  - 
    title: 'Challenge: improve your animation'
    challenge: true
  - 
    title: Animation using loops
  - 
    title: Monyet mengambang
  - 
    title: Memantul asteroid
  - 
    title: Bintang yang bersinar
  - 
    title: 'Tantangan: buat animasi Anda sendiri'
    challenge: true
  - 
    title: What next?
