---
title: Hilang dalam ruang
theme: hijau
hero_image: gambar / hilang-dalam-ruang.png
description: Pelajari cara memprogram animasi Anda sendiri!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
duration: 2
listed: true
copyedit: true
ingredient: false
curriculum: 1, desain-0, pemrograman-1, phys-comp-0, manufacture-0, community-0
interests: ruang
technologies: menggaruk
site_areas: proyek
hardware: ''
software: menggaruk
version: 4
last_tested: 2017-11-01
steps:
  - 
    title: pengantar
  - 
    title: Apa yang Anda butuhkan
  - 
    title: Membuat pesawat luar angkasa
  - 
    title: Beranimasi menggunakan loop
  - 
    title: Monyet mengambang
  - 
    title: Memantul asteroid
  - 
    title: Bintang yang bersinar
  - 
    title: 'Tantangan: buat animasi Anda sendiri'
