---
title: Izgubljeni v vesolju
hero_image: images/lost-in-space.png
description: Nauči se, kako sprogramirati svojo lastno animacijo!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4.1.3
last_tested: 2018-09-26
steps:
  - 
    title: Uvod
  - 
    title: Animacija vesoljske ladje
  - 
    title: 'Izziv: izboljšaj svojo animacijo'
    challenge: true
  - 
    title: Animiranje z uporabo zank
  - 
    title: Plavajoča opica
  - 
    title: Odbojni asteroid
  - 
    title: Sijoča ​​zvezda
  - 
    title: 'Izziv: Izdelaj svojo animacijo'
    challenge: true
  - 
    title: Kaj sledi?
