---
title: Ztraceni ve vesmíru
theme: zelená
hero_image: images/lost-in-space.png
description: V této lekci se naučíš, jak vytvářet vlastní animace!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
duration: 2
listed: true
copyedit: true
ingredient: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: vesmír
technologies: scratch
site_areas: projekty
hardware: ''
software: scratch
version: 4
last_tested: 2017-11-01
steps:
  - 
    title: Úvod
  - 
    title: Co budeš potřebovat
  - 
    title: Animování kosmické lodi
  - 
    title: Animování pomocí smyčky
  - 
    title: Plovoucí opice
  - 
    title: Odrážející se asteroid
  - 
    title: Zářící hvězda
  - 
    title: 'Výzva: Vytvoř si svou vlastní animaci'
