---
title: Ztraceni ve vesmíru
hero_image: images/lost-in-space.png
description: V této lekci se naučíš, jak vytvářet vlastní animace!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4
last_tested: 2017-11-01
steps:
  - 
    title: Úvod
  - 
    title: Animating a spaceship
  - 
    title: 'Challenge: improve your animation'
    challenge: true
  - 
    title: Animation using loops
  - 
    title: Plovoucí opice
  - 
    title: Odrážející se asteroid
  - 
    title: Zářící hvězda
  - 
    title: 'Výzva: Vytvoř si svou vlastní animaci'
    challenge: true
  - 
    title: What next?
