---
title: Perdidos en el espacio
hero_image: images/lost-in-space.png
description: '¡Vas a aprender a programar tu propia animación!'
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4
last_tested: 2017-11-01
steps:
  - 
    title: Perdidos en el espacio
  - 
    title: Animación de una nave espacial
  - 
    title: 'Desafío: Mejora tu animación'
    challenge: true
  - 
    title: Animar utilizando bucles
  - 
    title: Mono flotante
  - 
    title: Un asteroide que rebota
  - 
    title: Una estrella brillante
  - 
    title: 'Desafío: Haz tu propia animación'
    challenge: true
  - 
    title: What next?
