---
title: تائه في الفضاء
hero_image: images/lost-in-space.png
description: تعلَّم كيف تُبرمج الرسم المتحرك!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4.1.3
last_tested: 2018-09-26
steps:
  - 
    title: المقدمة
  - 
    title: تحريك سفينة فضاء
  - 
    title: 'Challenge: improve your animation'
    challenge: true
  - 
    title: Animation using loops
  - 
    title: قرد سابح
  - 
    title: كويكب يرتدّ
  - 
    title: نجم متلألئ
  - 
    title: 'تحدي: اصنع رسمتك المتحركة'
    challenge: true
  - 
    title: What next?
