---
title: 우주에서 길을 잃다
hero_image: images/lost-in-space.png
description: 나만의 애니메이션을 만드는 법을 배워봅시다!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4
last_tested: 2018-09-26
steps:
  - 
    title: 들어가며
  - 
    title: 우주선 움직이기
  - 
    title: '우주선 움직이기'
    challenge: true
  - 
    title: 반복하기를 사용한 움직임
  - 
    title: 떠다니는 원숭이
  - 
    title: 튀어다니는 소행성
  - 
    title: 빛나는 별
  - 
    title: '도전: 나만의 애니메이션을 만들어보세요'
    challenge: true
  - 
    title: What next?
