---
title: Stratený vo vesmíre
hero_image: images/lost-in-space.png
description: Ideš sa naučiť ako naprogramovať vlastnú animáciu.
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4
last_tested: 2017-11-01
steps:
  - 
    title: Stratený vo vesmíre
  - 
    title: Animácia vesmírnej lode
  - 
    title: 'Výzva: vylepšite svoju animáciu'
    challenge: true
  - 
    title: Animácia pomocou slučiek
  - 
    title: Vznášajúca sa opica
  - 
    title: Skákací asteroid
  - 
    title: Žiariaca hviezda
  - 
    title: 'Výzva: vytvorte si vlastnú animáciu'
    challenge: true
  - 
    title: Kam ďalej?
