---
title: Hilang di angkasa
hero_image: imej / lost-in-space.png
description: Ketahui bagaimana untuk memprogram animasi anda sendiri!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: awal
version: 4.1.3
last_tested: 2018-09-26
steps:
  - 
    title: Pengenalan
  - 
    title: Animating a spaceship
  - 
    title: 'Challenge: improve your animation'
    challenge: true
  - 
    title: Animation using loops
  - 
    title: Monyet terapung
  - 
    title: Memantul asteroid
  - 
    title: Bintang bersinar
  - 
    title: 'Cabaran: buat animasi anda sendiri'
    challenge: true
  - 
    title: What next?
