---
title: Perduto nello Spazio
hero_image: images/lost-in-space.png
description: Impara a programmare la tua animazione!
original_url: https://projects.raspberrypi.org/en/projects/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4.1.3
last_tested: 2018-09-26
steps:
  - 
    title: Introduzione
  - 
    title: Animare un'astronave
  - 
    title: 'Animare usando i loop'
    challenge: true
  - 
    title: Scimmie Fluttuanti
  - 
    title: Asteroidi Rimbalzanti
  - 
    title: Stelle Splendenti
  - 
    title: 'Sfida: Crea la tua animazione'
  - 
    title: 'Sfida: crea la tua animazione'
    challenge: true
  - 
    title: E adesso?
