---
title: Perduto nello Spazio
hero_image: images/lost-in-space.png
description: Impara a programmare la tua animazione!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4
last_tested: 2017-11-01
steps:
  - 
    title: Introduzione
  - 
    title: Animare un'astronave
  - 
    title: 'Sfida: migliora la tua animazione'
    challenge: true
  - 
    title: Animazioni usando i cicli
  - 
    title: Scimmietta fluttuante
  - 
    title: Asteroide che rimbalza
  - 
    title: Stella splendente
  - 
    title: 'Sfida: crea la tua animazione'
    challenge: true
  - 
    title: What next?
