---
title: "අභ්‍යවකාශයේ අතරමං වීම\n"
hero_image: images / lost-in-space.png
description: ඔබේම සජීවිකරණ(animation) වැඩසටහනක්(program එකක්) සාදන්නේ කෙසේදැයි ඉගෙන ගන්න!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
listed: true
copyedit: true
technologies: scratch
version: 4.1.3
last_tested: 2018-09-26
steps:
  - 
    title: හැදින්වීම
  - 
    title: අභ්‍යවකාශ යානයක්(spaceship) සජීවිකරණය(animation) කිරීම
  - 
    title: 'අභියෝගය: ඔබේ සජීවිකරණය වැඩි දියුණු කරන්න'
    challenge: true
  - 
    title: ලූප(loops) භාවිතා කරමින් සජීවිකරණය(animation)
  - 
    title: පාවෙන වඳුරා
  - 
    title: ග‍්‍රහකයක් පැන්නවීම(bouncing)
  - 
    title: දිදුලන තරුව
  - 
    title: 'අභියෝගය: ඔබේම සජීවීකරණයක් සාදන්න'
    challenge: true
  - 
    title: ඊලඟට කුමක්ද?
