---
title: Uzayda kayboldum
theme: yeşil
hero_image: images / kayıp-in-space.png
description: Kendi animasyonunuzu nasıl programlayacağınızı öğrenin!
original_url: https://www.codeclubprojects.org/en-GB/scratch/lost-in-space
duration: 2
listed: true
copyedit: true
ingredient: false
curriculum: 1, tasarım-0, programlama-1, fiz-comp-0, üretim-0, topluluk-0
interests: uzay
technologies: çizik
site_areas: projeler
hardware: ''
software: çizik
version: 4
last_tested: 2017/11/01
steps:
  - 
    title: Giriş
  - 
    title: Neye ihtiyacınız olacak?
  - 
    title: Bir uzay gemisini canlandırma
  - 
    title: Döngüler kullanarak animasyon
  - 
    title: Yüzen maymun
  - 
    title: Zıplayan asteroit
  - 
    title: Parlayan yıldız
  - 
    title: 'Zorluk: kendi animasyonunuzu yaratın'
